### ISSUE TITLE
一点想法

### ISSUE THREAD

**Issue by yodang19880804** [cobble19/takeaway#1]
首先感谢作者！
我对你的项目非常感兴趣，但是这个项目的文档十分缺少，理解起来有一定的难度。
另外，作者有想法重构项目吗？（springboot + springmvc + mybatis）

**Comment by cobble19** [comment]
工作这么多年, 一直都在用XML来配置, 全部或者核心用注解的方式还在学习. 
等下次重构的时候, 或许会考虑, 多谢提醒. 
此项目因为服务不同的目的(目标)经过好多次的变动, 内容比较混乱.大部分是我一个在做, 人又有点不太长进, 还没有形成稳定或者清晰的目标, 文档短期内没有.
